name = "MyProject"
uuid = "b6623268-9a17-423c-b045-25aa7927e6ad"
authors = ["Jesse Perla <jesseperla@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
